name: Get and Commit Comfy Nodes

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Fetch comfy nodes data
        run: python .github/scripts/fetch_comfy_nodes.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .ci/comfy/*.json
          git commit -m "chore: update comfy nodes data" || echo "No changes to commit"
          git push